<?php /**
 * @author Shoaib
 * @copyright 2017
 */
 ?>

<form id="doc-form" name="doc-form" method="post" action="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/sfupload/upload',array('form_key' => Mage::getSingleton('core/session')->getFormKey(),'order_id'=>$this->getOrder()->getId())); ?>" enctype="multipart/form-data">

<label>Select Attachment</label>
<input type="file" title="File" name="docname">
<label>Attachment Name</label>
<input type="text" title="image_name" name="image_name">
<label>Attachment Comments</label>
<input type="text" title="image_comments" name="image_comments">
<button type="submit" title="Save"><span>Upload</span></button>                    
</form>