<?php

if(isset($_POST['docname']))
{
    try
    {      
        $path = Mage::getBaseDir().DS.'customer_documents'.DS;  //desitnation directory    
        $fname = $_FILES['docname']['name']; //file name                       
        $uploader = new Varien_File_Uploader('docname'); //load class
        $uploader->setAllowedExtensions(array('doc','pdf','txt','docx')); //Allowed extension for file
        $uploader->setAllowCreateFolders(true); //for creating the directory if not exists
        $uploader->setAllowRenameFiles(false); //if true, uploaded file's name will be changed, if file with the same name already exists directory.
        $uploader->setFilesDispersion(false);
        $uploader->save($path,$fname); //save the file on the specified path
        
    }
    catch (Exception $e)
    {
        echo 'Error Message: '.$e->getMessage();
    }
}

 ?>

<form id="doc-form" name="doc-form" method="post" action="" enctype="multipart/form-data">
<label>Upload Document</label>
<input type="file" title="File" name="docname">
<button type="submit" title="Save"><span>Upload</span></button>                    
</form>
